### ISSUE TITLE
LoFi Mockup

### ISSUE THREAD

**Issue by andyl** [bugmark/website#2]
Create a LoFi Mockup for the bugmark.net website.  Post prototypes using Balsalmiq and InVision.

Start by: 
- posting a google spreadsheet with short list of comparable websites
- participate in discussion of desired website features and styles

Outcomes:
- [x] Balsalmiq wireframes - posted to repo
- [x] InVision mockups - posted to repo
- [x] Respond to feeback and discussion on Bugmark mailing list and IRC
- [ ] Stretch goal: create a Bugmark icon

**Comment by snehasi** [comment]
Here are few websites I liked:
https://docs.google.com/spreadsheets/d/1tFOZwpfvT8Seo1dCK06U7-LG3C3nl1feTgvIEYZBAqs/edit?usp=sharing

The features I feel would be useful are:
- A responsive website, adapts to small screens.
- A chat bot for 24/7 customer support . Multiple ways to reach out to the Bugmark team.
- Related bugs for a developer already working on a bug fix.
- Extremely easy UI -  so that a user who just wants to invest in an existing bug can do so without needing to go through all the bug features.
- Developer and investor reviews.
- User should be able to search for bugs with some tags.
- Linked Github or developer account.

Other backend features:
- Secure payments link and wallets for each user.
- A refund process if the bug goes unfixed.

**Comment by GeorgLink** [comment]
Thank you @snehasi.

Regarding the features you suggest, I would group them as follows:

## Most important for website
- A responsive website, adapts to small screens.
- Developer and investor reviews.

### My own suggestions for the website
- Explanation of what Bugmark is
- Use cases for Bugmark
- A page that explains how Bugmark works internally
- A comparison page of Bugmark with other market types

## Least important for website
- A chat bot for 24/7 customer support . Multiple ways to reach out to the Bugmark team.

## Part of Bugmark app, not website
- Related bugs for a developer already working on a bug fix.
- Extremely easy UI - so that a user who just wants to invest in an existing bug can do so without needing to go through all the bug features.
- User should be able to search for bugs with some tags.
- Linked Github or developer account.
- Secure payments link and wallets for each user.
- A refund process if the bug goes unfixed. (Bugmark operates as a futures market, with no money back)

**Comment by dmarti** [comment]
@GeorgLink The "refund" question is a good one.  People will be interested in cashing out their successful investments and might look for "refund" -- especially a user who buys UNFIXED then makes a profit when the bug goes unfixed might be looking for "refund".

So I would add

 * free-form search (so that we can check unsuccessful searches to improve our terminology)

**Comment by snehasi** [comment]
@GeorgLink @dmarti -
Thanks for the feedback, working on it. 
For uploading mockups and wireframe, should I make a PR by making a fork of this repo or make a new branch in it?

**Comment by andyl** [comment]
Overall: I endorse the organization recommendations of @GeorgLink .  The responsive requirement is very good.  (Bootstrap4 handles this nicely).  

@snehasi thanks for posting the spreadsheet please give write-access to me, @GeorgLink and @dmarti 

All of you have write access to the website repo.  Let's keep a `master` and `dev` branch.  Anyone can merge WIP into `dev`, and Andy can merge `dev` into `master`.  We deploy from `master` to github pages.  (deploy tooling is currently defined as part of  #3)  For your personal WIP, make a branch `dev_<yourname>` (`dev_andy`, `dev_sneha`, etc.) them submit a PR to merge into `dev`.

Does that sound OK?

**Comment by snehasi** [comment]
@andyl - yeah this is fine.

@Everyone: 
- I've uploaded the wireframe for the homepage to dev_sneha. 

- For other pages, I need to look into more features of the app. Here is a quick summary of how I usually approach building web apps and sites : https://medium.com/@sneha.si/melo-by-design-74da7be1e4f

- I see that the documentation is mostly incomplete right now. So, I would really find it helpful to work on some documentation and in the process learn how the web app works, before attempting the Project, Offers and Issues page.
Could someone kindly direct me to the doc issues I should approach first?

Thanks!

**Comment by GeorgLink** [comment]
Thank you @snehasi 

See comment on the pull request.

**Comment by andyl** [comment]
Done.
